### ISSUE TITLE
Shipston forcing data required for LSTM

### ISSUE THREAD

**Issue by shmh40** [ai4er-cdt/flood_risk_shipston#17]
We would like forcing data for Shipston for the following features.
Ideally we would have an average daily value for each feature over the whole Shipston basin, from ~1970 to 2020.

**Currently in the model:**

- [x] Total precipitation  
- [x] Air temperature
- [ ] Potential evaporation
- [ ] Surface downward shortwave radiation
- [ ] Specific humidity 

**Potential to be added to the model**

- [ ] Surface downward longwave radiation
- [ ] Potential energy 
- [ ] Surface pressure 
- [ ] Convective fraction 
- [ ] u wind component (latitudinal wind, W-E) 
- [ ] v wind component (longitudinal wind, N-S)

**Comment by shmh40** [comment]
List of possible data sources (thanks Simon M/Luke/Marc)

UK water resources portal: https://eip.ceh.ac.uk/hydrology/water-resources/ [No data for the area - Ira]
Centre for Environmental Data Analysis (CEDA): https://www.ceda.ac.uk/
Environment Agency data search portal: https://data.gov.uk/search?filters%5Bpublisher%5D=Environment+Agency
National River Flow Archive: https://nrfa.ceh.ac.uk/ [Similar data to Wisky but more coarse in time - Ira]
Land Use: UK gov land use registry/Aerial Photography

Other resources:
Google Earth Engine: https://earthengine.google.com/ [looking into it - Ira, Arduin]
QGIS software: https://qgis.org/en/site/
LiDAR (?)

**Comment by herbiebradley** [comment]
Update on the most useful features.

I ran a 5 layer LSTM model on several different feature combinations, both with a random single basin from CAMELS-GB and with multiple basins. All feature combinations were repeated 3 times with different random seeds and the results were averaged.

| Features                                            | Single-Basin NSE | % Improvment on Temp. + Precip. | Multi-Basin NSE | % Improvment on Temp. + Precip. |
|-----------------------------------------------------|----------------------|--------------------|---------------------|--------------------|
| Temp. + Precip.                                     | 0.95467              | 0                  | 0.839267            | 0                  |
| Temp. + Precip + Humidity                           | 0.9668               | 1.27               | 0.8474              | 0.969              |
| Temp. + Precip + Windspeed                          | 0.9624               | 0.81               | 0.849               | 1.16               |
| Temp. + Precip + Shortwave Rad                      | 0.964                | 0.98               | 0.8536              | 1.708              |
| Temp. + Precip + Peti                               | 0.9669               | 1.28               | 0.8465              | 0.862              |
| Temp. + Precip + Peti + Humidity                    | 0.9677               | 1.365              | 0.8532              | 1.66               |
| Temp. + Precip + Humidity + Shortwave               |                      |                    | 0.8556              | 1.946              |
| Temp. + Precip + Humid. + Short. + Peti + Windspeed | 0.9619               | 0.757              | 0.8684              | 3.47               |

Although the results have slight differences with single basin vs multiple basin, I believe we can conclude:

1. The variance in basin discharge is almost completely explained by temperature and precipitation - adding other forcings only gives marginal improvements.
2. Humidity and Peti give basically the same performance improvement, so we only really need humidity for Shipston.
3. Shortwave radiation and Windspeed may give slight performance improvements over Temp. + Precip + Humidity, so may be useful for Shipston. If a nearby weather station has these values that would be good.

In addition, since we have found surprisingly good results (NSE of 0.96) using only a single-basin model, this may be the most practical way of predicting Shipston's flow with decent accuracy in the next few weeks.
