### ISSUE TITLE
EA Questions for Friday 30th meeting

### ISSUE THREAD

**Issue by luke-scot** [ai4er-cdt/flood_risk_shipston#22]

**Comment by herbiebradley** [comment]
Maybe we can ask Vicki before the meeting:
The CAMELS-GB dataset contains a static basin attribute "discharges", which denotes the "mean discharges (daily discharges into water courses from water companies and other discharge permit holders reported to the Environment Agency) in mm per day". It may not be the most predictive attribute but since it's from the EA it's probably worth asking if they have this for Shipston.

**Comment by herbiebradley** [comment]
Actually ignore the above - CAMELS-GB's discharge attribute has too many NaNs in it to reliably use so it would not really be useful to obtain that information.
