### ISSUE TITLE
Run-off to flow relationship

### ISSUE THREAD

**Issue by luke-scot** [ai4er-cdt/flood_risk_shipston#24]
Looking for relationship once the run-off data is found (from Simon M?)

**Comment by Croydon-Brixton** [comment]
Hey everyone,
I've got updates on the run-off data. As it turns out the "discharge_vol" variable in Camels GB actually already corresponds to the "flow" variable that the NRFA uses (c.f. screenshot below). Therefore, the variable that we're already predicting to is already flow, rather than run-off and with @mja2106 script we should be able to connect the flow directly to the river stage.

This closes the workstream. 
Maybe instead of this workstream, we could try and see what simpler models would produce for the (other variables in Camels GB) to (flow) relationship? This way we would have another baseline to compare to? Happy for other ideas and inputs.

![image](https://user-images.githubusercontent.com/19754061/97551544-0356ae80-19cb-11eb-9860-7dbf56aa151b.png)

**Comment by mataln** [comment]
I'll put training/prediction scripts into src/models instead of the notebook when I get chance
